spring:
  application:
    name: zuul
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

zuul:
  routes:
    data-processing.url: http://localhost:8081/
    photos-processing.url: http://localhost:8082/
  sensitive-headers: false

ribbon.eureka.enabled: false