spring:
  application:
    name: zuul
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

zuul.routes.data-processing.url: http://localhost:8081
ribbon.eureka.enabled: false