server:
  protocol: http
  host: 127.0.0.1
  servlet.contextPath: /
  port: 8081
#  ssl:
#    key-store: ${NAUTILUS_SSL_STORE}
#    key-store-password: ${NAUTILUS_SSL_PASSWORD}
#    keyStoreType: PKCS12
#    keyAlias: tomcat

spring:
  main:
    banner-mode: "off"
  application:
    name: data-processing

photos:
  path: upload/
  max: 10

servlet.management.contextPath: /actuator
eureka.instance.statusPageUrlPath: /index
eureka.instance.healthCheckUrlPath: /index

logging:
  level:
    com.netflix.eureka: 'OFF'
