server:
  protocol: http
  host: localhost
  contextPath: /nautilus
  port: 8080
#  ssl:
#    key-store: ${NAUTILUS_SSL_STORE}
#    key-store-password: ${NAUTILUS_SSL_PASSWORD}
#    keyStoreType: PKCS12
#    keyAlias: tomcat

management.contextPath: /actuator
upload.path: upload/