server:
  protocol: http
  host: localhost
  port: 8070
#  ssl:
#    key-store: ${NAUTILUS_SSL_STORE}
#    key-store-password: ${NAUTILUS_SSL_PASSWORD}
#    keyStoreType: PKCS12
#    keyAlias: tomcat

upload.path: upload/