server:
  protocol: http
  host: 127.0.0.1
  servlet.contextPath: /
  port: 8082

spring:
  main:
    banner-mode: "off"
  application:
    name: photos-processing

photos:
  path: upload/
  max: 10

servlet.management.contextPath: /actuator
eureka.instance.statusPageUrlPath: /index
eureka.instance.healthCheckUrlPath: /index

logging:
  level:
    com.netflix.eureka: 'OFF'
